API_BASE_URL = "http://10.19.10.65:8105"
ACCESS_TOKEN = "ab5p_P6hzJ-MM_03gK2mQpmsUblkyxmsj2hdz6pZ2TMhu73TYGSBirZH"

[postgres]
host = "10.19.10.57"
port = 5432
database = "orionprod"
user = "deyvid.amorim"
password = "YKr7Cf_EmHP77Q"
