API_BASE_URL = "http://10.19.10.65:8105"
ACCESS_TOKEN = "ab5p_P6hzJ-MM_03gK2mQpmsUblkyxmsj2hdz6pZ2TMhu73TYGSBirZH"

[oracle]
user = "DEYVID_AMORIM"
password = "VZDfMis6FxFI0Q"
host = "192.168.1.2"
port = 1521
service_name = "SANKHYAW"